# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: hexo setup and generate
      run: make setup generate

    - name: rsync deployment
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete-after
        path: public/
        remote_path: /public/
        remote_host: oak.bjrm.de
        remote_user: deploy_kalembe
        remote_key: ${{ secrets.DEPLOY_KEY }}

